_BATCH_ACCOUNT_NAME = 'mbertbatch17'
_BATCH_ACCOUNT_KEY = 'RM6sltVh2SNAPJE7w/ZQMJALBTS8dCU+0YfoCfFHQFGuV6Sgbkh4xek+SgXhT6R+R95fd2Ubandz33zRFcJX4g=='
_BATCH_ACCOUNT_URL = 'https://mbertbatch17.canadaeast.batch.azure.com'
_STORAGE_ACCOUNT_NAME = 'mbertsa17'
_STORAGE_ACCOUNT_KEY = 'Yui9/YHkGWXE60SGz2dyAH4xkz5vzCUyVdS0kDso7YvrFYeuKP/FZ6hbq9cwIjnYR5tKwfN6YH0E/QwzfnhmMw=='
_POOL_ID = 'X12toXMLPool'
_POOL_NODE_COUNT = 1
_JOB_ID = 'X12toXMLJob'
